%avgtotrue = plot(mask_rates,average_to_true,color = "red")
subplot(2,3,1)
hist(results(:,1))
xlabel("p-1 = 2","FontSize", 22)
subplot(2,3,2)
hist(results(:,2))
xlabel("p-1 = 5","FontSize", 22)
subplot(2,3,3)
hist(results(:,3))
xlabel("p-1 = 10","FontSize", 22)
subplot(2,3,4)
hist(results(:,4))
xlabel("p-1 = 25","FontSize", 22)
subplot(2,3,5)
hist(results(:,5))
xlabel("p-1 = 100","FontSize", 22)

%avgmasked = plot(mask_rates,average_num_hidden,color = "black")
